# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
app:
  host-url: http://localhost:8080
  test-mail: ${APP_TEST_MAIL:jira4jr@gmail.com}
  templates-update-cache: 5s
  mail-sending-props:
    core-pool-size: 8
    max-pool-size: 100

spring:
  init:
    mode: never

  messages:
    basename: messages
    encoding: UTF-8

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate   # валидируем схему, но не генерим
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jira}
    username: ${SPRING_DATASOURCE_USERNAME:jira}
    password: ${SPRING_DATASOURCE_PASSWORD:JiraRush}

  liquibase:
    change-log: classpath:db/changelog.sql

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

  cache:
    cache-names: users
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=5m

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
            scope:
              - user:email
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          gitlab:
            client-id: ${OAUTH_GITLAB_CLIENT_ID}
            client-secret: ${OAUTH_GITLAB_CLIENT_SECRET}
            client-name: GitLab
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - read_user
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: email

  sql:
    init:
      mode: never   # отключаем, т.к. используем Liquibase

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  thymeleaf:
    check-template-location: false

  web:
    resources:
      add-mappings: false

logging:
  level:
    root: WARN
    com.javarush.jira: DEBUG
    com.javarush.jira.common.config.MvcConfig: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server:
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  swagger-ui:
    path: /doc